---
- name: include_tasks create_realm_zonegroup_zone_lists.yml
  include_tasks: create_realm_zonegroup_zone_lists.yml

- name: include multisite checks
  include_tasks: checks.yml

# Include the tasks depending on the zone type
- name: include_tasks master.yml
  include_tasks: master.yml

- name: include_tasks secondary.yml
  include_tasks: secondary.yml

- name: include_tasks start_radosgw.yml for zonesecondary rgws
  include_tasks: ../start_radosgw.yml
  when:
    - not containerized_deployment | bool

- name: include_tasks start_docker_rgw.yml for zonesecondary rgws
  include_tasks: ../start_docker_rgw.yml
  when:
    - containerized_deployment | bool
